@baseURL = http://localhost:8000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2ODg1NzgwMzQsImlhdCI6MTY4ODQ5MTYzNH0.03hUcVbQUOn6MX-FoWFcThvPF9PBgozJIhYWc0V9E6Q

### Test API
GET {{baseURL}}/health
Content-Type: application/json

### User Register
POST {{baseURL}}/user/register
Content-Type: application/json

{
  "name": "John Doe",
  "phone": "1234567890",
  "email": "johndoe@example.com",
  "password": "password123"
}

### User Login
POST {{baseURL}}/user/login
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "password123"
}

### Create Contact
POST {{baseURL}}/contact
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2ODg1NzgwMzQsImlhdCI6MTY4ODQ5MTYzNH0.03hUcVbQUOn6MX-FoWFcThvPF9PBgozJIhYWc0V9E6Q

{
  "name": "neo ai",
  "phone_number": "1234567890"
}
