@baseURL = http://localhost:8000

### Test API
GET {{baseURL}}/health
Content-Type: application/json

### User Register
POST {{baseURL}}/user/register
Content-Type: application/json

{
  "name": "John Doe",
  "phone": "1234567890",
  "email": "johndoe@example.com",
  "password": "password123"
}

